### ISSUE TITLE
California Roll doesn't show up

### ISSUE THREAD

**Issue by GlenKPeterson** [IMalyugin/dont-starve-mod-craftpot#4]
![Screenshot from 2023-03-16 23-27-44](https://user-images.githubusercontent.com/2416031/225908010-4e7b667b-84ae-47e7-a145-c954f66f05d0.png)

I put in the ingredients for California Roll, but it doesn't show up in Craftpot!

The recipe is different for DST vs. SW.  I'm playing DST, latest branch (was Wilson beta).
https://dontstarve.fandom.com/wiki/California_Roll

Maybe this is an issue with some weird state due to snapping tills (I can see the highlight in the screenshot)?

I've been trying to make every dish possible, which I guess is a good test.  I've probably made 80% of them and this is the first time Craftpot didn't work perfectly.  Thank you for this great mod!  The game should have this built-in.

**Comment by GlenKPeterson** [comment]
I just checked: the recipe worked.
![Screenshot from 2023-03-17 09-14-19](https://user-images.githubusercontent.com/2416031/225915203-c01946ad-773a-4b4e-9887-366725e59eaf.png)

**Comment by IMalyugin** [comment]
It doesn't matter that there are differences in recipes, basically Craftpot "hacks" recipe book with meta tables. The algorithm is far from perfect, and works best when used with less strict conditions. Will try to find time to look into the issue, could be something simple.

Funny enough, early version of Craftpot used brute force to hack recipes, I just passed 999 of every known ingredient and then tried mixing them up and reducing amount till it worked.

Are you using "OCD Highlight option"? I think it's called something like "Hide uncooked", it was meant to be part of the quest to cook every dish, but I don't believe it ever became popular :)

**Comment by GlenKPeterson** [comment]
> Will try to find time to look into the issue, could be something simple.
Thanks!  I may try looking at the code too, but I haven't so far, so don't count on it.

> Early version of Craftpot used brute force to hack recipes, I just passed 999 of every known ingredient and then tried mixing them up and reducing amount till it worked.

Hah!  Yeah, first make it work, then make it better.  Great way to code.

> Are you using "OCD Highlight option"? I think it's called something like "Hide uncooked", it was meant to be part of the quest to cook every dish, but I don't believe it ever became popular :)

I will look for it - thanks!

**Comment by IMalyugin** [comment]
Most likely fixed by #8
